name: 'Heroku Production Deploy'
​
on:
  push:
    branches:
      - master
​
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.7751cad8-f0f8-4b18-a2e9-d76a8b75d456}}//key
          heroku_app_name: ${{secrets.ancient-ridge-06187}}
          heroku_email: ${{secrets.javanslem@gmail.com}}